import sequelize from "./config/sequelize.config.js";
import { Address } from "./models/address.model.js";
import { Operator } from "./models/operator.model.js";
import { Order } from "./models/order.model.js";
import { OrderItem } from "./models/orderItem.model.js";
import { Product } from "./models/product.model.js";
import { Shipper } from "./models/shipper.model.js";
import { Shop } from "./models/shop.model.js";
import { User } from "./models/user.model.js";

async function insertShops() {
    try {
        const shops = [
            {
                shopName: "Tech World",
                ownerID: 1,
                taxCode: "123456789",
                shopEmail: "techworld@example.com",
                shopPhone: "0987654321",
                shopDescription: "Your go-to place for the latest tech gadgets.",
                shopPickUpAddress: "123 Tech Street, Hanoi",
                shopStatus: "active",
                shopAvatar: "https://example.com/tech-avatar.jpg",
                shopOperationHours: "9:00 AM - 9:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Electronics",
                shopRating: 4.5,
                shopBankAccountNumber: "9876543210",
                shopBankName: "Vietcombank",
            },
            {
                shopName: "Fashion Hub",
                ownerID: 2,
                taxCode: "234567890",
                shopEmail: "fashionhub@example.com",
                shopPhone: "0976543210",
                shopDescription: "Trendy fashion for all ages.",
                shopPickUpAddress: "45 Fashion Street, Ho Chi Minh",
                shopStatus: "active",
                shopAvatar: "https://example.com/fashion-avatar.jpg",
                shopOperationHours: "10:00 AM - 8:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Clothing",
                shopRating: 4.2,
                shopBankAccountNumber: "8765432109",
                shopBankName: "TPBank",
            },
            {
                shopName: "Home Essentials",
                ownerID: 3,
                taxCode: "345678901",
                shopEmail: "homeessentials@example.com",
                shopPhone: "0965432109",
                shopDescription: "All your home needs in one place.",
                shopPickUpAddress: "78 Home Street, Da Nang",
                shopStatus: "pending",
                shopAvatar: "https://example.com/home-avatar.jpg",
                shopOperationHours: "8:00 AM - 10:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Home & Living",
                shopRating: 4.0,
                shopBankAccountNumber: "7654321098",
                shopBankName: "MB Bank",
            },
            {
                shopName: "Gourmet Delights",
                ownerID: 4,
                taxCode: "456789012",
                shopEmail: "gourmet@example.com",
                shopPhone: "0954321098",
                shopDescription: "Delicious gourmet food and drinks.",
                shopPickUpAddress: "12 Food Court, Hue",
                shopStatus: "active",
                shopAvatar: "https://example.com/food-avatar.jpg",
                shopOperationHours: "7:00 AM - 11:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Food & Beverages",
                shopRating: 4.7,
                shopBankAccountNumber: "6543210987",
                shopBankName: "BIDV",
            },
            {
                shopName: "Fitness Pro",
                ownerID: 5,
                taxCode: "567890123",
                shopEmail: "fitnesspro@example.com",
                shopPhone: "0943210987",
                shopDescription: "The best place for fitness gear.",
                shopPickUpAddress: "33 Gym Street, Nha Trang",
                shopStatus: "active",
                shopAvatar: "https://example.com/fitness-avatar.jpg",
                shopOperationHours: "6:00 AM - 10:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Fitness & Sports",
                shopRating: 4.8,
                shopBankAccountNumber: "5432109876",
                shopBankName: "Agribank",
            },
            {
                shopName: "Book Nook",
                ownerID: 6,
                taxCode: "678901234",
                shopEmail: "booknook@example.com",
                shopPhone: "0932109876",
                shopDescription: "A cozy place for book lovers.",
                shopPickUpAddress: "66 Book Street, Can Tho",
                shopStatus: "active",
                shopAvatar: "https://example.com/book-avatar.jpg",
                shopOperationHours: "9:00 AM - 8:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Books",
                shopRating: 4.6,
                shopBankAccountNumber: "4321098765",
                shopBankName: "ACB",
            },
            {
                shopName: "Art Gallery",
                ownerID: 7,
                taxCode: "789012345",
                shopEmail: "artgallery@example.com",
                shopPhone: "0921098765",
                shopDescription: "Discover beautiful art pieces.",
                shopPickUpAddress: "99 Art Street, Hoi An",
                shopStatus: "active",
                shopAvatar: "https://example.com/art-avatar.jpg",
                shopOperationHours: "10:00 AM - 7:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Arts & Crafts",
                shopRating: 4.4,
                shopBankAccountNumber: "3210987654",
                shopBankName: "Sacombank",
            },
            {
                shopName: "Pet Paradise",
                ownerID: 8,
                taxCode: "890123456",
                shopEmail: "petparadise@example.com",
                shopPhone: "0910987654",
                shopDescription: "Everything your pet needs.",
                shopPickUpAddress: "11 Pet Street, Vung Tau",
                shopStatus: "active",
                shopAvatar: "https://example.com/pet-avatar.jpg",
                shopOperationHours: "8:00 AM - 9:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Pet Supplies",
                shopRating: 4.3,
                shopBankAccountNumber: "2109876543",
                shopBankName: "Eximbank",
            },
            {
                shopName: "Toy Land",
                ownerID: 9,
                taxCode: "901234567",
                shopEmail: "toyland@example.com",
                shopPhone: "0909876543",
                shopDescription: "A world of toys for kids.",
                shopPickUpAddress: "22 Toy Street, Hai Phong",
                shopStatus: "active",
                shopAvatar: "https://example.com/toy-avatar.jpg",
                shopOperationHours: "9:30 AM - 8:30 PM",
                shopJoinedDate: new Date(),
                businessType: "Toys & Games",
                shopRating: 4.5,
                shopBankAccountNumber: "1098765432",
                shopBankName: "VPBank",
            },
            {
                shopName: "Music Mania",
                ownerID: 10,
                taxCode: "012345678",
                shopEmail: "musicmania@example.com",
                shopPhone: "0998765432",
                shopDescription: "All your music needs in one place.",
                shopPickUpAddress: "44 Music Street, Phu Quoc",
                shopStatus: "active",
                shopAvatar: "https://example.com/music-avatar.jpg",
                shopOperationHours: "10:30 AM - 9:30 PM",
                shopJoinedDate: new Date(),
                businessType: "Music & Instruments",
                shopRating: 4.1,
                shopBankAccountNumber: "0987654321",
                shopBankName: "Shinhan Bank",
            },
            {
                shopName: "Garden Bliss",
                ownerID: 11,
                taxCode: "112233445",
                shopEmail: "gardenbliss@example.com",
                shopPhone: "0987123456",
                shopDescription: "Everything for your gardening needs.",
                shopPickUpAddress: "55 Garden Street, Sapa",
                shopStatus: "active",
                shopAvatar: "https://example.com/garden-avatar.jpg",
                shopOperationHours: "8:30 AM - 7:30 PM",
                shopJoinedDate: new Date(),
                businessType: "Home & Garden",
                shopRating: 4.6,
                shopBankAccountNumber: "1234567890",
                shopBankName: "DongA Bank",
            },
            {
                shopName: "Coffee Corner",
                ownerID: 12,
                taxCode: "223344556",
                shopEmail: "coffeecorner@example.com",
                shopPhone: "0976234567",
                shopDescription: "Your daily dose of caffeine.",
                shopPickUpAddress: "77 Coffee Street, Buon Ma Thuot",
                shopStatus: "active",
                shopAvatar: "https://example.com/coffee-avatar.jpg",
                shopOperationHours: "7:00 AM - 6:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Food & Beverages",
                shopRating: 4.9,
                shopBankAccountNumber: "2345678901",
                shopBankName: "OCB",
            },
            {
                shopName: "Travel Treasures",
                ownerID: 13,
                taxCode: "334455667",
                shopEmail: "traveltreasures@example.com",
                shopPhone: "0965345678",
                shopDescription: "Everything you need for your next adventure.",
                shopPickUpAddress: "88 Travel Street, Ha Long",
                shopStatus: "active",
                shopAvatar: "https://example.com/travel-avatar.jpg",
                shopOperationHours: "9:00 AM - 8:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Travel & Outdoors",
                shopRating: 4.4,
                shopBankAccountNumber: "3456789012",
                shopBankName: "LienVietPostBank",
            },
            {
                shopName: "Creative Studio",
                ownerID: 14,
                taxCode: "445566778",
                shopEmail: "creativestudio@example.com",
                shopPhone: "0954456789",
                shopDescription: "Unleash your creativity.",
                shopPickUpAddress: "99 Creative Street, Dalat",
                shopStatus: "active",
                shopAvatar: "https://example.com/creative-avatar.jpg",
                shopOperationHours: "10:00 AM - 9:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Arts & Crafts",
                shopRating: 4.7,
                shopBankAccountNumber: "4567890123",
                shopBankName: "Maritime Bank",
            },
            {
                shopName: "Health Hub",
                ownerID: 15,
                taxCode: "556677889",
                shopEmail: "healthhub@example.com",
                shopPhone: "0943567890",
                shopDescription: "Your one-stop shop for health and wellness.",
                shopPickUpAddress: "10 Health Street, Vinh",
                shopStatus: "active",
                shopAvatar: "https://example.com/health-avatar.jpg",
                shopOperationHours: "8:00 AM - 7:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Health & Beauty",
                shopRating: 4.3,
                shopBankAccountNumber: "5678901234",
                shopBankName: "SeABank",
            },
            {
                shopName: "Vintage Vibes",
                ownerID: 16,
                taxCode: "667788990",
                shopEmail: "vintagevibes@example.com",
                shopPhone: "0932678901",
                shopDescription: "Unique vintage finds.",
                shopPickUpAddress: "11 Vintage Street, My Tho",
                shopStatus: "active",
                shopAvatar: "https://example.com/vintage-avatar.jpg",
                shopOperationHours: "11:00 AM - 8:00 PM",
                shopJoinedDate: new Date(),
                businessType: "Clothing",
                shopRating: 4.8,
                shopBankAccountNumber: "6789012345",
                shopBankName: "Bac A Bank",
            },
            {
                shopName: "Tool Time",
                ownerID: 17,
                taxCode: "778899001",
                shopEmail: "tooltime@example.com",
                shopPhone: "0921789012",
                shopDescription: "All the tools you need for your projects.",
                shopPickUpAddress: "22 Tool Street, Rach Gia",
                shopStatus: "active",
                shopAvatar: "https://example.com/tool-avatar.jpg",
                shopOperationHours: "7:30 AM - 6:30 PM",
                shopJoinedDate: new Date(),
                businessType: "Hardware",
                shopRating: 4.2,
                shopBankAccountNumber: "7890123456",
                shopBankName: "PVcomBank",
            },
            {
                shopName: "Kids Kingdom",
                ownerID: 18,
                taxCode: "889900112",
                shopEmail: "kidskingdom@example.com",
                shopPhone: "0910890123",
                shopDescription: "Everything for kids, from toys to clothes.",
                shopPickUpAddress: "33 Kids Street, Long Xuyen",
                shopStatus: "active",
                shopAvatar: "https://example.com/kids-avatar.jpg",
                shopOperationHours: "9:30 AM - 7:30 PM",
                shopJoinedDate: new Date(),
                businessType: "Children's Products",
                shopRating: 4.5,
                shopBankAccountNumber: "8901234567",
                shopBankName: "GPBank",
            },
            {
                shopName: "Sports Station",
                ownerID: 19,
                taxCode: "990011223",
                shopEmail: "sportsstation@example.com",
                shopPhone: "0999901234",
                shopDescription: "All your sports equipment needs.",
                shopPickUpAddress: "44 Sports Street, Cao Lanh",
                shopStatus: "active",
                shopAvatar: "https://example.com/sports-avatar.jpg",
                shopOperationHours: "6:30 AM - 9:30 PM",
                shopJoinedDate: new Date(),
                businessType: "Fitness & Sports",
                shopRating: 4.6,
                shopBankAccountNumber: "9012345678",
                shopBankName: "SCB",
            },
        ];

        await Shop.bulkCreate(shops);
        console.log("Shops inserted successfully.");
    } catch (error) {
        console.error("Error inserting shops:", error);
    }
}

//insertShops();

// async function insertOperators() {
//     try {
//         await sequelize.sync(); // Ensure database schema is up to date

//         const operators = [{ operatorName: "John Doe" }, { operatorName: "Jane Smith" }];

//         await Operator.bulkCreate(operators);
//         console.log("Operators inserted successfully.");
//     } catch (error) {
//         console.error("Error inserting operators:", error);
//     } finally {
//         await sequelize.close(); // Close the connection
//     }
// }

// insertOperators();

const insertShippers = async () => {
    try {
        await sequelize.authenticate();
        console.log("Kết nối với database thành công.");

        const generateRandomDate = (start, end) => {
            return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))
                .toISOString()
                .slice(0, 10);
        };

        const shippers = [
            {
                name: "Nguyễn Văn Tèo",
                gender: "Nam",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Hà Nội",
                address: "123 Đường Láng, Đống Đa, Hà Nội",
                phone: "0912345671",
                cccd: "012345678901",
                email: "teo.nguyen@example.com",
                status: "active",
                activityArea: "Hà Nội",
                shippingMethod: "Xe máy",
            },
            {
                name: "Trần Thị Hoa",
                gender: "Nữ",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "TP. Hồ Chí Minh",
                address: "456 Nguyễn Trãi, Quận 5, TP.HCM",
                phone: "0987654321",
                cccd: "112233445566",
                email: "hoa.tran@example.com",
                status: "active",
                activityArea: "TP.HCM",
                shippingMethod: "Xe máy",
            },
            {
                name: "Lê Văn Ba",
                gender: "Nam",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Đà Nẵng",
                address: "789 Lê Duẩn, Hải Châu, Đà Nẵng",
                phone: "0909876543",
                cccd: "223344556677",
                email: "ba.le@example.com",
                status: "inactive",
                activityArea: "Đà Nẵng",
                shippingMethod: "Xe đạp",
            },
            {
                name: "Phạm Thị Tư",
                gender: "Nữ",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Hải Phòng",
                address: "101 Điện Biên Phủ, Lê Chân, Hải Phòng",
                phone: "0976543210",
                cccd: "334455667788",
                email: "tu.pham@example.com",
                status: "pending",
                activityArea: "Hải Phòng",
                shippingMethod: "Xe máy",
            },
            {
                name: "Hoàng Minh Đức",
                gender: "Nam",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Cần Thơ",
                address: "1122 Trần Hưng Đạo, Ninh Kiều, Cần Thơ",
                phone: "0965432109",
                cccd: "445566778899",
                email: "duc.hoang@example.com",
                status: "active",
                activityArea: "Cần Thơ",
                shippingMethod: "Xe máy",
            },
            {
                name: "Vũ Thị Hà",
                gender: "Nữ",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Huế",
                address: "3344 Hùng Vương, TP. Huế",
                phone: "0954321098",
                cccd: "556677889900",
                email: "ha.vu@example.com",
                status: "inactive",
                activityArea: "Huế",
                shippingMethod: "Xe đạp",
            },
            {
                name: "Đỗ Xuân Trường",
                gender: "Nam",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Bắc Ninh",
                address: "5566 Nguyễn Trãi, TP. Bắc Ninh",
                phone: "0943210987",
                cccd: "667788990011",
                email: "truong.do@example.com",
                status: "pending",
                activityArea: "Bắc Ninh",
                shippingMethod: "Xe máy",
            },
            {
                name: "Lý Thanh Mai",
                gender: "Nữ",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Vinh",
                address: "7788 Lê Hồng Phong, TP. Vinh",
                phone: "0932109876",
                cccd: "778899001122",
                email: "mai.ly@example.com",
                status: "active",
                activityArea: "Vinh",
                shippingMethod: "Xe máy",
            },
            {
                name: "Cao Hoàng Nam",
                gender: "Nam",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Nha Trang",
                address: "9900 Trần Phú, TP. Nha Trang",
                phone: "0921098765",
                cccd: "889900112233",
                email: "nam.cao@example.com",
                status: "inactive",
                activityArea: "Nha Trang",
                shippingMethod: "Xe đạp",
            },
            {
                name: "Phan Thu Thủy",
                gender: "Nữ",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Đà Lạt",
                address: "112 Nguyễn Du, TP. Đà Lạt",
                phone: "0910987654",
                cccd: "990011223344",
                email: "thuy.phan@example.com",
                status: "pending",
                activityArea: "Đà Lạt",
                shippingMethod: "Xe máy",
            },
            {
                name: "Trần Đình Khôi",
                gender: "Nam",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Hà Nội",
                address: "223 Nguyễn Khuyến, Đống Đa, Hà Nội",
                phone: "0978901234",
                cccd: "012345678912",
                email: "khoi.tran@example.com",
                status: "active",
                activityArea: "Hà Nội",
                shippingMethod: "Xe máy",
            },
            {
                name: "Lê Thị Phương",
                gender: "Nữ",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "TP. Hồ Chí Minh",
                address: "445 Pasteur, Quận 1, TP.HCM",
                phone: "0967890123",
                cccd: "123456789013",
                email: "phuong.le@example.com",
                status: "inactive",
                activityArea: "TP.HCM",
                shippingMethod: "Xe đạp",
            },
            {
                name: "Hoàng Văn Quyết",
                gender: "Nam",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Hải Phòng",
                address: "667 Trần Phú, Ngô Quyền, Hải Phòng",
                phone: "0956789012",
                cccd: "234567890124",
                email: "quyet.hoang@example.com",
                status: "pending",
                activityArea: "Hải Phòng",
                shippingMethod: "Xe máy",
            },
            {
                name: "Phạm Thị Quỳnh Anh",
                gender: "Nữ",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Cần Thơ",
                address: "889 Cách Mạng Tháng 8, TP. Cần Thơ",
                phone: "0945678901",
                cccd: "345678901235",
                email: "quynhanh.pham@example.com",
                status: "active",
                activityArea: "Cần Thơ",
                shippingMethod: "Xe máy",
            },
            {
                name: "Đặng Tiến Dũng",
                gender: "Nam",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Đà Nẵng",
                address: "1012 Hùng Vương, Hải Châu, Đà Nẵng",
                phone: "0934567890",
                cccd: "456789012346",
                email: "dung.dang@example.com",
                status: "inactive",
                activityArea: "Đà Nẵng",
                shippingMethod: "Xe máy",
            },
            {
                name: "Vũ Ngọc Ánh",
                gender: "Nữ",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Huế",
                address: "1214 Trần Cao Vân, TP. Huế",
                phone: "0923456789",
                cccd: "567890123457",
                email: "ngocanh.vu@example.com",
                status: "pending",
                activityArea: "Huế",
                shippingMethod: "Xe đạp",
            },
            {
                name: "Bùi Thế Anh",
                gender: "Nam",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Bắc Ninh",
                address: "1416 Lý Thái Tổ, TP. Bắc Ninh",
                phone: "0913456789",
                cccd: "678901234568",
                email: "theanh.bui@example.com",
                status: "active",
                activityArea: "Bắc Ninh",
                shippingMethod: "Xe máy",
            },
            {
                name: "Ngô Thùy Linh",
                gender: "Nữ",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Vinh",
                address: "1618 Nguyễn Thị Minh Khai, TP. Vinh",
                phone: "0902345678",
                cccd: "789012345679",
                email: "thuylinh.ngo@example.com",
                status: "inactive",
                activityArea: "Vinh",
                shippingMethod: "Xe máy",
            },
            {
                name: "Lê Cao Cường",
                gender: "Nam",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Nha Trang",
                address: "1820 Thống Nhất, TP. Nha Trang",
                phone: "0971234567",
                cccd: "890123456780",
                email: "caocuong.le@example.com",
                status: "pending",
                activityArea: "Nha Trang",
                shippingMethod: "Xe máy",
            },
            {
                name: "Phạm Thị Diệu",
                gender: "Nữ",
                dateOfBirth: generateRandomDate(new Date(1980, 0, 1), new Date(2000, 11, 31)),
                hometown: "Đà Lạt",
                address: "2022 Hai Bà Trưng, TP. Đà Lạt",
                phone: "0960123456",
                cccd: "901234567891",
                email: "dieu.pham@example.com",
                status: "active",
                activityArea: "Đà Lạt",
                shippingMethod: "Xe đạp",
            },
        ];

        await Shipper.bulkCreate(shippers);
        console.log("Đã tạo thành công 20 shippers.");
    } catch (error) {
        console.error("Lỗi khi tạo dữ liệu:", error);
    }
};

// insertShippers();
const insertUsers = async () => {
    try {
        await sequelize.authenticate();
        console.log("Kết nối với database thành công.");

        const users = [
            {
                fullName: "Nguyễn Văn A",
                dateOfBirth: "1990-01-15",
                gender: "male",
                userEmail: "nguyenvana@example.com",
                userPhone: "0987654321",
                userCitizenID: "123456789",
                userAddress: "Số 10, Đường Láng, Hà Nội",
                identificationNumber: "ID100001",
                idCardFrontFile: "https://example.com/id_front_1.jpg",
                idCardBackFile: "https://example.com/id_back_1.jpg",
                status: "active",
            },
            {
                fullName: "Trần Thị B",
                dateOfBirth: "1992-03-22",
                gender: "female",
                userEmail: "tranthib@example.com",
                userPhone: "0987654322",
                userCitizenID: "123456790",
                userAddress: "Số 12, Đường Trần Hưng Đạo, Hà Nội",
                identificationNumber: "ID100002",
                idCardFrontFile: "https://example.com/id_front_2.jpg",
                idCardBackFile: "https://example.com/id_back_2.jpg",
                status: "inactive",
            },
            {
                fullName: "Lê Văn C",
                dateOfBirth: "1988-07-10",
                gender: "male",
                userEmail: "levanc@example.com",
                userPhone: "0987654323",
                userCitizenID: "123456791",
                userAddress: "Số 15, Đường Nguyễn Chí Thanh, TP. Hồ Chí Minh",
                identificationNumber: "ID100003",
                idCardFrontFile: "https://example.com/id_front_3.jpg",
                idCardBackFile: "https://example.com/id_back_3.jpg",
                status: "active",
            },
            {
                fullName: "Phạm Thu D",
                dateOfBirth: "1995-06-05",
                gender: "female",
                userEmail: "phamthud@example.com",
                userPhone: "0987654324",
                userCitizenID: "123456792",
                userAddress: "Số 20, Đường Quang Trung, Đà Nẵng",
                identificationNumber: "ID100004",
                idCardFrontFile: "https://example.com/id_front_4.jpg",
                idCardBackFile: "https://example.com/id_back_4.jpg",
                status: "suspended",
            },
            {
                fullName: "Đỗ Minh E",
                dateOfBirth: "1985-12-01",
                gender: "male",
                userEmail: "dominhe@example.com",
                userPhone: "0987654325",
                userCitizenID: "123456793",
                userAddress: "Số 5, Đường Lê Lợi, Hải Phòng",
                identificationNumber: "ID100005",
                idCardFrontFile: "https://example.com/id_front_5.jpg",
                idCardBackFile: "https://example.com/id_back_5.jpg",
                status: "active",
            },
            {
                fullName: "Hoàng Anh F",
                dateOfBirth: "1998-09-17",
                gender: "other",
                userEmail: "hoanganhf@example.com",
                userPhone: "0987654326",
                userCitizenID: "123456794",
                userAddress: "Số 8, Đường Võ Văn Kiệt, Cần Thơ",
                identificationNumber: "ID100006",
                idCardFrontFile: "https://example.com/id_front_6.jpg",
                idCardBackFile: "https://example.com/id_back_6.jpg",
                status: "inactive",
            },
            {
                fullName: "Nguyễn Thị G",
                dateOfBirth: "1993-04-30",
                gender: "female",
                userEmail: "nguyenthig@example.com",
                userPhone: "0987654327",
                userCitizenID: "123456795",
                userAddress: "Số 25, Đường Hoàng Hoa Thám, Huế",
                identificationNumber: "ID100007",
                idCardFrontFile: "https://example.com/id_front_7.jpg",
                idCardBackFile: "https://example.com/id_back_7.jpg",
                status: "active",
            },
            {
                fullName: "Trịnh Văn H",
                dateOfBirth: "1987-02-14",
                gender: "male",
                userEmail: "trinhvanh@example.com",
                userPhone: "0987654328",
                userCitizenID: "123456796",
                userAddress: "Số 18, Đường Nguyễn Văn Cừ, Bắc Ninh",
                identificationNumber: "ID100008",
                idCardFrontFile: "https://example.com/id_front_8.jpg",
                idCardBackFile: "https://example.com/id_back_8.jpg",
                status: "suspended",
            },
            {
                fullName: "Bùi Hữu I",
                dateOfBirth: "1991-08-25",
                gender: "male",
                userEmail: "buihuui@example.com",
                userPhone: "0987654329",
                userCitizenID: "123456797",
                userAddress: "Số 30, Đường Phạm Văn Đồng, Vinh",
                identificationNumber: "ID100009",
                idCardFrontFile: "https://example.com/id_front_9.jpg",
                idCardBackFile: "https://example.com/id_back_9.jpg",
                status: "active",
            },
            {
                fullName: "Đặng Thị J",
                dateOfBirth: "1986-05-19",
                gender: "female",
                userEmail: "dangthij@example.com",
                userPhone: "0987654330",
                userCitizenID: "123456798",
                userAddress: "Số 40, Đường Trường Chinh, Nha Trang",
                identificationNumber: "ID100010",
                idCardFrontFile: "https://example.com/id_front_10.jpg",
                idCardBackFile: "https://example.com/id_back_10.jpg",
                status: "inactive",
            },
            {
                fullName: "Lý Văn K",
                dateOfBirth: "1994-11-03",
                gender: "male",
                userEmail: "lyvank@example.com",
                userPhone: "0987654331",
                userCitizenID: "123456799",
                userAddress: "Số 7, Đường 30/4, Cần Thơ",
                identificationNumber: "ID100011",
                idCardFrontFile: "https://example.com/id_front_11.jpg",
                idCardBackFile: "https://example.com/id_back_11.jpg",
                status: "active",
            },
            {
                fullName: "Vũ Thị L",
                dateOfBirth: "1989-09-28",
                gender: "female",
                userEmail: "vuthil@example.com",
                userPhone: "0987654332",
                userCitizenID: "123456800",
                userAddress: "Số 11, Đường Trần Phú, Huế",
                identificationNumber: "ID100012",
                idCardFrontFile: "https://example.com/id_front_12.jpg",
                idCardBackFile: "https://example.com/id_back_12.jpg",
                status: "suspended",
            },
            {
                fullName: "Đào Văn M",
                dateOfBirth: "1996-03-12",
                gender: "male",
                userEmail: "daovanm@example.com",
                userPhone: "0987654333",
                userCitizenID: "123456801",
                userAddress: "Số 14, Đường Hùng Vương, Đà Lạt",
                identificationNumber: "ID100013",
                idCardFrontFile: "https://example.com/id_front_13.jpg",
                idCardBackFile: "https://example.com/id_back_13.jpg",
                status: "active",
            },
            {
                fullName: "Phan Thị N",
                dateOfBirth: "1984-07-07",
                gender: "female",
                userEmail: "phanthin@example.com",
                userPhone: "0987654334",
                userCitizenID: "123456802",
                userAddress: "Số 22, Đường 2/9, Đà Nẵng",
                identificationNumber: "ID100014",
                idCardFrontFile: "https://example.com/id_front_14.jpg",
                idCardBackFile: "https://example.com/id_back_14.jpg",
                status: "inactive",
            },
            {
                fullName: "Hồ Văn O",
                dateOfBirth: "1997-01-29",
                gender: "male",
                userEmail: "hovano@example.com",
                userPhone: "0987654335",
                userCitizenID: "123456803",
                userAddress: "Số 35, Đường Lê Hồng Phong, Quy Nhơn",
                identificationNumber: "ID100015",
                idCardFrontFile: "https://example.com/id_front_15.jpg",
                idCardBackFile: "https://example.com/id_back_15.jpg",
                status: "active",
            },
            {
                fullName: "Lương Thị P",
                dateOfBirth: "1990-05-23",
                gender: "female",
                userEmail: "luongthip@example.com",
                userPhone: "0987654336",
                userCitizenID: "123456804",
                userAddress: "Số 42, Đường Nguyễn Thị Minh Khai, Vũng Tàu",
                identificationNumber: "ID100016",
                idCardFrontFile: "https://example.com/id_front_16.jpg",
                idCardBackFile: "https://example.com/id_back_16.jpg",
                status: "suspended",
            },
            {
                fullName: "Trần Quốc Q",
                dateOfBirth: "1983-11-15",
                gender: "male",
                userEmail: "tranquocq@example.com",
                userPhone: "0987654337",
                userCitizenID: "123456805",
                userAddress: "Số 50, Đường 3/2, TP. Hồ Chí Minh",
                identificationNumber: "ID100017",
                idCardFrontFile: "https://example.com/id_front_17.jpg",
                idCardBackFile: "https://example.com/id_back_17.jpg",
                status: "active",
            },
            {
                fullName: "Hoàng Thị R",
                dateOfBirth: "1999-08-09",
                gender: "female",
                userEmail: "hoangthir@example.com",
                userPhone: "0987654338",
                userCitizenID: "123456806",
                userAddress: "Số 55, Đường Trần Hưng Đạo, Hội An",
                identificationNumber: "ID100018",
                idCardFrontFile: "https://example.com/id_front_18.jpg",
                idCardBackFile: "https://example.com/id_back_18.jpg",
                status: "inactive",
            },
            {
                fullName: "Nguyễn Hữu S",
                dateOfBirth: "1992-02-27",
                gender: "male",
                userEmail: "nguyenhuus@example.com",
                userPhone: "0987654339",
                userCitizenID: "123456807",
                userAddress: "Số 60, Đường Lê Duẩn, Huế",
                identificationNumber: "ID100019",
                idCardFrontFile: "https://example.com/id_front_19.jpg",
                idCardBackFile: "https://example.com/id_back_19.jpg",
                status: "active",
            },
            {
                fullName: "Phạm Thị T",
                dateOfBirth: "1985-06-11",
                gender: "female",
                userEmail: "phamthit@example.com",
                userPhone: "0987654340",
                userCitizenID: "123456808",
                userAddress: "Số 66, Đường 3 Tháng 2, Đà Lạt",
                identificationNumber: "ID100020",
                idCardFrontFile: "https://example.com/id_front_20.jpg",
                idCardBackFile: "https://example.com/id_back_20.jpg",
                status: "suspended",
            },
        ];

        await User.bulkCreate(users);
        console.log("Thêm 10 users vào database thành công.");

        // await sequelize.close();
        // console.log("Đóng kết nối database.");
    } catch (error) {
        console.error("Lỗi khi chèn users:", error);
    }
};

// insertUsers();

const insertAddresses = async () => {
    try {
        await sequelize.authenticate();
        console.log("Kết nối với database thành công.");

        const addresses = [
            {
                user_id: 1,
                fullName: "Nguyễn Văn A",
                phone: "0987654321",
                province: "Hà Nội",
                city: "Hoàn Kiếm",
                district: "Ba Đình",
                ward: "Phường Cống Vị",
                street: "Số 10, Đường Láng",
                default: true,
            },
            {
                user_id: 2,
                fullName: "Trần Thị B",
                phone: "0987654322",
                province: "Hà Nội",
                city: "Hai Bà Trưng",
                district: "Đống Đa",
                ward: "Phường Khâm Thiên",
                street: "Số 20, Đường Trần Hưng Đạo",
                default: false,
            },
            {
                user_id: 3,
                fullName: "Lê Văn C",
                phone: "0987654323",
                province: "TP. Hồ Chí Minh",
                city: "Quận 1",
                district: "Bình Thạnh",
                ward: "Phường 15",
                street: "Số 15, Đường Nguyễn Chí Thanh",
                default: true,
            },
            {
                user_id: 4,
                fullName: "Phạm Thu D",
                phone: "0987654324",
                province: "Đà Nẵng",
                city: "Hải Châu",
                district: "Thanh Khê",
                ward: "Phường Hòa Khê",
                street: "Số 30, Đường Quang Trung",
                default: false,
            },
            {
                user_id: 5,
                fullName: "Đỗ Minh E",
                phone: "0987654325",
                province: "Hải Phòng",
                city: "Ngô Quyền",
                district: "Lê Chân",
                ward: "Phường Dư Hàng",
                street: "Số 5, Đường Lê Lợi",
                default: true,
            },
            {
                user_id: 6,
                fullName: "Hoàng Anh F",
                phone: "0987654326",
                province: "Cần Thơ",
                city: "Ninh Kiều",
                district: "Bình Thủy",
                ward: "Phường An Thới",
                street: "Số 8, Đường Võ Văn Kiệt",
                default: false,
            },
            {
                user_id: 7,
                fullName: "Nguyễn Thị G",
                phone: "0987654327",
                province: "Huế",
                city: "Thừa Thiên Huế",
                district: "Hương Thủy",
                ward: "Phường Thuận An",
                street: "Số 25, Đường Hoàng Hoa Thám",
                default: true,
            },
            {
                user_id: 8,
                fullName: "Trịnh Văn H",
                phone: "0987654328",
                province: "Bắc Ninh",
                city: "Từ Sơn",
                district: "Tiên Du",
                ward: "Phường Đông Ngàn",
                street: "Số 18, Đường Nguyễn Văn Cừ",
                default: false,
            },
            {
                user_id: 9,
                fullName: "Bùi Hữu I",
                phone: "0987654329",
                province: "Nghệ An",
                city: "Vinh",
                district: "Cửa Lò",
                ward: "Phường Nghi Hương",
                street: "Số 30, Đường Phạm Văn Đồng",
                default: true,
            },
            {
                user_id: 10,
                fullName: "Đặng Thị J",
                phone: "0987654330",
                province: "Khánh Hòa",
                city: "Nha Trang",
                district: "Diên Khánh",
                ward: "Phường Vĩnh Nguyên",
                street: "Số 40, Đường Trường Chinh",
                default: false,
            },
            {
                user_id: 11,
                fullName: "Lý Minh K",
                phone: "0987654331",
                province: "Đồng Nai",
                city: "Biên Hòa",
                district: "Long Thành",
                ward: "Phường An Bình",
                street: "Số 50, Đường Nguyễn Ái Quốc",
                default: true,
            },
            {
                user_id: 12,
                fullName: "Nguyễn Hữu L",
                phone: "0987654332",
                province: "Bình Dương",
                city: "Thủ Dầu Một",
                district: "Thuận An",
                ward: "Phường An Phú",
                street: "Số 60, Đường Đại Lộ Bình Dương",
                default: false,
            },
            {
                user_id: 13,
                fullName: "Phan Thị M",
                phone: "0987654333",
                province: "Quảng Ninh",
                city: "Hạ Long",
                district: "Cẩm Phả",
                ward: "Phường Bãi Cháy",
                street: "Số 70, Đường Trần Phú",
                default: true,
            },
            {
                user_id: 14,
                fullName: "Trương Văn N",
                phone: "0987654334",
                province: "Lâm Đồng",
                city: "Đà Lạt",
                district: "Bảo Lộc",
                ward: "Phường 7",
                street: "Số 80, Đường Lê Duẩn",
                default: false,
            },
            {
                user_id: 15,
                fullName: "Vũ Thanh O",
                phone: "0987654335",
                province: "Quảng Nam",
                city: "Tam Kỳ",
                district: "Điện Bàn",
                ward: "Phường Thanh Hà",
                street: "Số 90, Đường Phan Bội Châu",
                default: true,
            },
            {
                user_id: 16,
                fullName: "Lê Đình P",
                phone: "0987654336",
                province: "Thái Bình",
                city: "Thái Bình",
                district: "Kiến Xương",
                ward: "Phường Đông Hưng",
                street: "Số 100, Đường Nguyễn Du",
                default: false,
            },
            {
                user_id: 17,
                fullName: "Phạm Văn Q",
                phone: "0987654337",
                province: "Bắc Giang",
                city: "Bắc Giang",
                district: "Hiệp Hòa",
                ward: "Phường Cẩm Đông",
                street: "Số 110, Đường Bạch Đằng",
                default: true,
            },
            {
                user_id: 18,
                fullName: "Đặng Thị R",
                phone: "0987654338",
                province: "Sơn La",
                city: "Mộc Châu",
                district: "Yên Châu",
                ward: "Phường Chiềng Cọ",
                street: "Số 120, Đường Tô Hiệu",
                default: false,
            },
        ];

        await Address.bulkCreate(addresses); // Sử dụng trực tiếp Address model
        console.log("Thêm 18 địa chỉ vào database thành công.");

        // await sequelize.close();
        // console.log("Đóng kết nối database.");
    } catch (error) {
        console.error("Lỗi khi chèn địa chỉ:", error);
    }
};

// insertAddresses();

const products = [
    {
        shop_id: 1,
        product_name: "Áo sơ mi nam",
        description: "Áo sơ mi nam cao cấp",
        status: "active",
        price: 500000,
        quantity: 10,
    },
    {
        shop_id: 1,
        product_name: "Quần jeans nam",
        description: "Quần jeans phong cách",
        status: "active",
        price: 700000,
        quantity: 15,
    },
    {
        shop_id: 2,
        product_name: "Giày thể thao",
        description: "Giày thể thao thoáng khí",
        status: "active",
        price: 1200000,
        quantity: 20,
    },
    {
        shop_id: 2,
        product_name: "Balo du lịch",
        description: "Balo thời trang",
        status: "active",
        price: 850000,
        quantity: 12,
    },
    {
        shop_id: 3,
        product_name: "Nước hoa nam",
        description: "Hương thơm nam tính",
        status: "active",
        price: 1500000,
        quantity: 8,
    },
    {
        shop_id: 3,
        product_name: "Đồng hồ thông minh",
        description: "Đồng hồ đa chức năng",
        status: "active",
        price: 2500000,
        quantity: 5,
    },
    {
        shop_id: 4,
        product_name: "Bút ký cao cấp",
        description: "Bút ký sang trọng",
        status: "active",
        price: 300000,
        quantity: 25,
    },
    {
        shop_id: 4,
        product_name: "Sổ tay da",
        description: "Sổ tay doanh nhân",
        status: "active",
        price: 400000,
        quantity: 18,
    },
    {
        shop_id: 5,
        product_name: "Laptop gaming",
        description: "Laptop cấu hình cao",
        status: "active",
        price: 25000000,
        quantity: 3,
    },
    {
        shop_id: 5,
        product_name: "Chuột không dây",
        description: "Chuột gaming",
        status: "active",
        price: 600000,
        quantity: 30,
    },
    {
        shop_id: 6,
        product_name: "Loa Bluetooth",
        description: "Loa âm thanh sống động",
        status: "active",
        price: 900000,
        quantity: 22,
    },
    {
        shop_id: 6,
        product_name: "Tai nghe chống ồn",
        description: "Tai nghe chất lượng cao",
        status: "active",
        price: 2000000,
        quantity: 10,
    },
    {
        shop_id: 7,
        product_name: "Bình giữ nhiệt",
        description: "Bình giữ nhiệt inox",
        status: "active",
        price: 350000,
        quantity: 40,
    },
    {
        shop_id: 7,
        product_name: "Bộ dao nhà bếp",
        description: "Bộ dao inox cao cấp",
        status: "active",
        price: 750000,
        quantity: 15,
    },
    {
        shop_id: 8,
        product_name: "Bàn phím cơ",
        description: "Bàn phím cơ RGB",
        status: "active",
        price: 1800000,
        quantity: 7,
    },
    {
        shop_id: 8,
        product_name: "Máy pha cà phê",
        description: "Máy pha cà phê tự động",
        status: "active",
        price: 3200000,
        quantity: 4,
    },
    {
        shop_id: 9,
        product_name: "Sạc dự phòng",
        description: "Sạc nhanh 10000mAh",
        status: "active",
        price: 450000,
        quantity: 25,
    },
    {
        shop_id: 9,
        product_name: "Cáp sạc USB-C",
        description: "Cáp sạc nhanh",
        status: "active",
        price: 200000,
        quantity: 50,
    },
    {
        shop_id: 10,
        product_name: "Nồi chiên không dầu",
        description: "Nồi chiên công nghệ mới",
        status: "active",
        price: 2200000,
        quantity: 6,
    },
    {
        shop_id: 10,
        product_name: "Lò vi sóng",
        description: "Lò vi sóng điện tử",
        status: "active",
        price: 2800000,
        quantity: 3,
    },
    {
        shop_id: 11,
        product_name: "Máy giặt",
        description: "Máy giặt 9kg",
        status: "active",
        price: 8000000,
        quantity: 2,
    },
    {
        shop_id: 11,
        product_name: "Tủ lạnh",
        description: "Tủ lạnh inverter 300L",
        status: "active",
        price: 12000000,
        quantity: 2,
    },
    {
        shop_id: 12,
        product_name: "Bộ bàn ghế gỗ",
        description: "Bàn ghế gỗ cao cấp",
        status: "active",
        price: 5500000,
        quantity: 4,
    },
    {
        shop_id: 12,
        product_name: "Đèn LED để bàn",
        description: "Đèn học chống cận",
        status: "active",
        price: 500000,
        quantity: 30,
    },
    {
        shop_id: 13,
        product_name: "Tranh treo tường",
        description: "Tranh trang trí nghệ thuật",
        status: "active",
        price: 900000,
        quantity: 12,
    },
    {
        shop_id: 13,
        product_name: "Chăn ga gối đệm",
        description: "Bộ chăn ga cao cấp",
        status: "active",
        price: 3500000,
        quantity: 5,
    },
    {
        shop_id: 14,
        product_name: "Bộ dụng cụ làm vườn",
        description: "Bộ dụng cụ cầm tay",
        status: "active",
        price: 700000,
        quantity: 20,
    },
    {
        shop_id: 14,
        product_name: "Hạt giống rau sạch",
        description: "Hạt giống hữu cơ",
        status: "active",
        price: 150000,
        quantity: 100,
    },
];

const insertProducts = async () => {
    try {
        await sequelize.sync();
        await Product.bulkCreate(products);
        console.log("Dữ liệu sản phẩm đã được chèn thành công!");
    } catch (error) {
        console.error("Lỗi khi chèn dữ liệu sản phẩm:", error);
    }
};

// insertProducts();

const insertOrders = async () => {
    try {
        await sequelize.authenticate(); // Đảm bảo kết nối trước khi sync
        console.log("Kết nối với database thành công.");
        // Mảng dữ liệu đơn hàng (để dùng bulkCreate)
        const orders = [
            {
                shop_id: 1,
                customer_id: 2,
                shipper_id: 3,
                address_id: 1,
                productFee: 150000,
                shippingFee: 30000,
                status: "pending",
                total: 180000,
                note: "Giao hàng giờ hành chính",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "COD",
            },
            {
                shop_id: 2,
                customer_id: 5,
                shipper_id: 1,
                address_id: 3,
                productFee: 250000,
                shippingFee: 35000,
                status: "processing",
                total: 285000,
                note: "Gọi điện trước khi giao",
                payment_status: "paid",
                shipping_status: "shipping",
                payment_method: "Credit Card",
            },
            {
                shop_id: 3,
                customer_id: 1,
                shipper_id: 2,
                address_id: 2,
                productFee: 100000,
                shippingFee: 25000,
                status: "completed",
                total: 125000,
                note: "Giao hàng nhanh giúp mình",
                payment_status: "paid",
                shipping_status: "shipped",
                payment_method: "Bank Transfer",
            },
            {
                shop_id: 4,
                customer_id: 3,
                shipper_id: 4,
                address_id: 4,
                productFee: 50000,
                shippingFee: 15000,
                status: "cancelled",
                total: 65000,
                note: "Khách hàng hủy đơn",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "COD",
            },
            {
                shop_id: 5,
                customer_id: 4,
                shipper_id: 5,
                address_id: 5,
                productFee: 300000,
                shippingFee: 40000,
                status: "pending",
                total: 340000,
                note: "Không giao vào cuối tuần",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "Momo",
            },
            {
                shop_id: 1,
                customer_id: 6,
                shipper_id: 3,
                address_id: 6,
                productFee: 180000,
                shippingFee: 32000,
                status: "processing",
                total: 212000,
                note: "Kiểm tra kỹ hàng trước khi giao",
                payment_status: "paid",
                shipping_status: "shipping",
                payment_method: "Credit Card",
            },
            {
                shop_id: 2,
                customer_id: 7,
                shipper_id: 1,
                address_id: 7,
                productFee: 120000,
                shippingFee: 28000,
                status: "completed",
                total: 148000,
                note: "Hàng giao nhanh, cảm ơn shop",
                payment_status: "paid",
                shipping_status: "shipped",
                payment_method: "Bank Transfer",
            },
            {
                shop_id: 3,
                customer_id: 8,
                shipper_id: 2,
                address_id: 8,
                productFee: 70000,
                shippingFee: 20000,
                status: "cancelled",
                total: 90000,
                note: "Đổi ý không mua nữa",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "COD",
            },
            {
                shop_id: 4,
                customer_id: 9,
                shipper_id: 4,
                address_id: 9,
                productFee: 220000,
                shippingFee: 38000,
                status: "pending",
                total: 258000,
                note: "Giao hàng vào buổi tối",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "Momo",
            },
            {
                shop_id: 5,
                customer_id: 10,
                shipper_id: 5,
                address_id: 10,
                productFee: 280000,
                shippingFee: 42000,
                status: "processing",
                total: 322000,
                note: "Gói hàng cẩn thận giúp mình",
                payment_status: "paid",
                shipping_status: "shipping",
                payment_method: "Credit Card",
            },
            {
                shop_id: 1,
                customer_id: 11,
                shipper_id: 3,
                address_id: 1,
                productFee: 160000,
                shippingFee: 31000,
                status: "completed",
                total: 191000,
                note: "Cảm ơn shop, hàng đẹp",
                payment_status: "paid",
                shipping_status: "shipped",
                payment_method: "Bank Transfer",
            },
            {
                shop_id: 2,
                customer_id: 12,
                shipper_id: 1,
                address_id: 3,
                productFee: 60000,
                shippingFee: 18000,
                status: "cancelled",
                total: 78000,
                note: "Thay đổi địa chỉ giao hàng",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "COD",
            },
            {
                shop_id: 3,
                customer_id: 13,
                shipper_id: 2,
                address_id: 2,
                productFee: 230000,
                shippingFee: 39000,
                status: "pending",
                total: 269000,
                note: "Giao hàng nhanh giúp mình",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "Momo",
            },
            {
                shop_id: 4,
                customer_id: 14,
                shipper_id: 4,
                address_id: 4,
                productFee: 290000,
                shippingFee: 43000,
                status: "processing",
                total: 333000,
                note: "Gói hàng cẩn thận",
                payment_status: "paid",
                shipping_status: "shipping",
                payment_method: "Credit Card",
            },
            {
                shop_id: 5,
                customer_id: 15,
                shipper_id: 5,
                address_id: 5,
                productFee: 130000,
                shippingFee: 29000,
                status: "completed",
                total: 159000,
                note: "Hàng tốt, cảm ơn shop",
                payment_status: "paid",
                shipping_status: "shipped",
                payment_method: "Bank Transfer",
            },
            {
                shop_id: 1,
                customer_id: 16,
                shipper_id: 3,
                address_id: 6,
                productFee: 80000,
                shippingFee: 22000,
                status: "cancelled",
                total: 102000,
                note: "Hủy đơn vì hết hàng",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "COD",
            },
            {
                shop_id: 2,
                customer_id: 17,
                shipper_id: 1,
                address_id: 7,
                productFee: 240000,
                shippingFee: 40000,
                status: "pending",
                total: 280000,
                note: "Giao hàng đúng hẹn",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "Momo",
            },
            {
                shop_id: 3,
                customer_id: 18,
                shipper_id: 2,
                address_id: 8,
                productFee: 300000,
                shippingFee: 44000,
                status: "processing",
                total: 344000,
                note: "Kiểm tra hàng trước khi thanh toán",
                payment_status: "paid",
                shipping_status: "shipping",
                payment_method: "Credit Card",
            },
            {
                shop_id: 4,
                customer_id: 19,
                shipper_id: 4,
                address_id: 9,
                productFee: 140000,
                shippingFee: 30000,
                status: "completed",
                total: 170000,
                note: "Shop phục vụ tốt",
                payment_status: "paid",
                shipping_status: "shipped",
                payment_method: "Bank Transfer",
            },
            {
                shop_id: 5,
                customer_id: 20,
                shipper_id: 5,
                address_id: 10,
                productFee: 90000,
                shippingFee: 24000,
                status: "cancelled",
                total: 114000,
                note: "Không liên lạc được",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "COD",
            },
            {
                shop_id: 1,
                customer_id: 2,
                shipper_id: 3,
                address_id: 11,
                productFee: 170000,
                shippingFee: 33000,
                status: "pending",
                total: 203000,
                note: "Giao hàng giờ hành chính",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "COD",
            },
            {
                shop_id: 2,
                customer_id: 5,
                shipper_id: 1,
                address_id: 12,
                productFee: 260000,
                shippingFee: 36000,
                status: "processing",
                total: 296000,
                note: "Gọi điện trước khi giao",
                payment_status: "paid",
                shipping_status: "shipping",
                payment_method: "Credit Card",
            },
            {
                shop_id: 3,
                customer_id: 1,
                shipper_id: 2,
                address_id: 13,
                productFee: 110000,
                shippingFee: 26000,
                status: "completed",
                total: 136000,
                note: "Giao hàng nhanh giúp mình",
                payment_status: "paid",
                shipping_status: "shipped",
                payment_method: "Bank Transfer",
            },
            {
                shop_id: 4,
                customer_id: 3,
                shipper_id: 4,
                address_id: 14,
                productFee: 60000,
                shippingFee: 16000,
                status: "cancelled",
                total: 76000,
                note: "Khách hàng hủy đơn",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "COD",
            },
            {
                shop_id: 5,
                customer_id: 4,
                shipper_id: 5,
                address_id: 15,
                productFee: 310000,
                shippingFee: 41000,
                status: "pending",
                total: 351000,
                note: "Không giao vào cuối tuần",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "Momo",
            },
            {
                shop_id: 1,
                customer_id: 6,
                shipper_id: 3,
                address_id: 16,
                productFee: 190000,
                shippingFee: 33000,
                status: "processing",
                total: 223000,
                note: "Kiểm tra kỹ hàng trước khi giao",
                payment_status: "paid",
                shipping_status: "shipping",
                payment_method: "Credit Card",
            },
            {
                shop_id: 2,
                customer_id: 7,
                shipper_id: 1,
                address_id: 17,
                productFee: 130000,
                shippingFee: 29000,
                status: "completed",
                total: 159000,
                note: "Hàng giao nhanh, cảm ơn shop",
                payment_status: "paid",
                shipping_status: "shipped",
                payment_method: "Bank Transfer",
            },
            {
                shop_id: 3,
                customer_id: 8,
                shipper_id: 2,
                address_id: 18,
                productFee: 80000,
                shippingFee: 21000,
                status: "cancelled",
                total: 101000,
                note: "Đổi ý không mua nữa",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "COD",
            },
            {
                shop_id: 4,
                customer_id: 9,
                shipper_id: 4,
                address_id: 1,
                productFee: 230000,
                shippingFee: 39000,
                status: "pending",
                total: 269000,
                note: "Giao hàng vào buổi tối",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "Momo",
            },
            {
                shop_id: 5,
                customer_id: 10,
                shipper_id: 5,
                address_id: 2,
                productFee: 290000,
                shippingFee: 43000,
                status: "processing",
                total: 333000,
                note: "Gói hàng cẩn thận giúp mình",
                payment_status: "paid",
                shipping_status: "shipping",
                payment_method: "Credit Card",
            },
            {
                shop_id: 1,
                customer_id: 11,
                shipper_id: 3,
                address_id: 1,
                productFee: 170000,
                shippingFee: 32000,
                status: "completed",
                total: 202000,
                note: "Cảm ơn shop, hàng đẹp",
                payment_status: "paid",
                shipping_status: "shipped",
                payment_method: "Bank Transfer",
            },
            {
                shop_id: 2,
                customer_id: 12,
                shipper_id: 1,
                address_id: 3,
                productFee: 70000,
                shippingFee: 19000,
                status: "cancelled",
                total: 89000,
                note: "Thay đổi địa chỉ giao hàng",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "COD",
            },
            {
                shop_id: 3,
                customer_id: 13,
                shipper_id: 2,
                address_id: 2,
                productFee: 240000,
                shippingFee: 40000,
                status: "pending",
                total: 280000,
                note: "Giao hàng nhanh giúp mình",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "Momo",
            },
            {
                shop_id: 4,
                customer_id: 14,
                shipper_id: 4,
                address_id: 4,
                productFee: 300000,
                shippingFee: 44000,
                status: "processing",
                total: 344000,
                note: "Gói hàng cẩn thận",
                payment_status: "paid",
                shipping_status: "shipping",
                payment_method: "Credit Card",
            },
            {
                shop_id: 5,
                customer_id: 15,
                shipper_id: 5,
                address_id: 5,
                productFee: 140000,
                shippingFee: 30000,
                status: "completed",
                total: 170000,
                note: "Hàng tốt, cảm ơn shop",
                payment_status: "paid",
                shipping_status: "shipped",
                payment_method: "Bank Transfer",
            },
            {
                shop_id: 1,
                customer_id: 16,
                shipper_id: 3,
                address_id: 6,
                productFee: 90000,
                shippingFee: 23000,
                status: "cancelled",
                total: 113000,
                note: "Hủy đơn vì hết hàng",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "COD",
            },
            {
                shop_id: 2,
                customer_id: 17,
                shipper_id: 1,
                address_id: 7,
                productFee: 250000,
                shippingFee: 41000,
                status: "pending",
                total: 291000,
                note: "Giao hàng đúng hẹn",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "Momo",
            },
            {
                shop_id: 3,
                customer_id: 18,
                shipper_id: 2,
                address_id: 8,
                productFee: 310000,
                shippingFee: 45000,
                status: "processing",
                total: 355000,
                note: "Kiểm tra hàng trước khi thanh toán",
                payment_status: "paid",
                shipping_status: "shipping",
                payment_method: "Credit Card",
            },
            {
                shop_id: 4,
                customer_id: 19,
                shipper_id: 4,
                address_id: 9,
                productFee: 150000,
                shippingFee: 31000,
                status: "completed",
                total: 181000,
                note: "Shop phục vụ tốt",
                payment_status: "paid",
                shipping_status: "shipped",
                payment_method: "Bank Transfer",
            },
            {
                shop_id: 5,
                customer_id: 20,
                shipper_id: 5,
                address_id: 10,
                productFee: 100000,
                shippingFee: 25000,
                status: "cancelled",
                total: 125000,
                note: "Không liên lạc được",
                payment_status: "pending",
                shipping_status: "not_yet_shipped",
                payment_method: "COD",
            },
        ];

        // Sử dụng bulkCreate để chèn nhiều bản ghi cùng lúc
        await Order.bulkCreate(orders);

        console.log("Đã tạo thành công 40 đơn hàng.");
    } catch (error) {
        console.error("Lỗi khi tạo dữ liệu:", error);
    }
};

// insertOrders();

const orderItems = [
    { order_id: 1, product_id: 5, price: 150000, quantity: 2, total: 300000 },
    { order_id: 2, product_id: 8, price: 200000, quantity: 1, total: 200000 },
    { order_id: 3, product_id: 12, price: 50000, quantity: 4, total: 200000 },
    { order_id: 4, product_id: 3, price: 75000, quantity: 3, total: 225000 },
    { order_id: 5, product_id: 7, price: 120000, quantity: 2, total: 240000 },
    { order_id: 6, product_id: 10, price: 90000, quantity: 5, total: 450000 },
    { order_id: 7, product_id: 15, price: 110000, quantity: 2, total: 220000 },
    { order_id: 8, product_id: 6, price: 95000, quantity: 3, total: 285000 },
    { order_id: 9, product_id: 18, price: 65000, quantity: 4, total: 260000 },
    { order_id: 10, product_id: 20, price: 130000, quantity: 1, total: 130000 },
    { order_id: 11, product_id: 9, price: 85000, quantity: 2, total: 170000 },
    { order_id: 12, product_id: 14, price: 200000, quantity: 3, total: 600000 },
    { order_id: 13, product_id: 2, price: 300000, quantity: 1, total: 300000 },
    { order_id: 14, product_id: 4, price: 100000, quantity: 5, total: 500000 },
    { order_id: 15, product_id: 16, price: 125000, quantity: 2, total: 250000 },
    { order_id: 16, product_id: 1, price: 70000, quantity: 3, total: 210000 },
    { order_id: 17, product_id: 13, price: 140000, quantity: 2, total: 280000 },
    { order_id: 18, product_id: 11, price: 195000, quantity: 1, total: 195000 },
    { order_id: 19, product_id: 19, price: 175000, quantity: 2, total: 350000 },
    { order_id: 20, product_id: 17, price: 155000, quantity: 1, total: 155000 },
    { order_id: 21, product_id: 5, price: 160000, quantity: 2, total: 320000 },
    { order_id: 22, product_id: 8, price: 220000, quantity: 1, total: 220000 },
    { order_id: 23, product_id: 12, price: 55000, quantity: 4, total: 220000 },
    { order_id: 24, product_id: 3, price: 80000, quantity: 3, total: 240000 },
    { order_id: 25, product_id: 7, price: 130000, quantity: 2, total: 260000 },
    { order_id: 26, product_id: 10, price: 95000, quantity: 5, total: 475000 },
    { order_id: 27, product_id: 15, price: 115000, quantity: 2, total: 230000 },
    { order_id: 28, product_id: 6, price: 99000, quantity: 3, total: 297000 },
    { order_id: 29, product_id: 18, price: 68000, quantity: 4, total: 272000 },
    { order_id: 30, product_id: 20, price: 135000, quantity: 1, total: 135000 },
    { order_id: 31, product_id: 9, price: 89000, quantity: 2, total: 178000 },
    { order_id: 32, product_id: 14, price: 210000, quantity: 3, total: 630000 },
    { order_id: 33, product_id: 2, price: 310000, quantity: 1, total: 310000 },
    { order_id: 34, product_id: 4, price: 105000, quantity: 5, total: 525000 },
    { order_id: 35, product_id: 16, price: 130000, quantity: 2, total: 260000 },
    { order_id: 36, product_id: 1, price: 75000, quantity: 3, total: 225000 },
    { order_id: 37, product_id: 13, price: 145000, quantity: 2, total: 290000 },
    { order_id: 38, product_id: 11, price: 200000, quantity: 1, total: 200000 },
    { order_id: 39, product_id: 19, price: 180000, quantity: 2, total: 360000 },
    { order_id: 40, product_id: 17, price: 160000, quantity: 1, total: 160000 },
];

const insertOrderItems1 = async () => {
    try {
        await sequelize.sync();
        await OrderItem.bulkCreate(orderItems);
        console.log("Đã chèn 50 OrderItems vào cơ sở dữ liệu!");
    } catch (error) {
        console.error("Lỗi khi chèn dữ liệu:", error);
    }
};

// insertOrderItems1();

const insertOrderItems = async () => {
    try {
        await sequelize.authenticate();
        console.log("Kết nối với database thành công.");
        const orderItems = [
            { order_id: 1, product_id: 1, price: 50000, quantity: 2, total: 100000 },
            { order_id: 1, product_id: 2, price: 30000, quantity: 1, total: 30000 },

            { order_id: 2, product_id: 3, price: 120000, quantity: 1, total: 120000 },
            { order_id: 2, product_id: 4, price: 80000, quantity: 2, total: 160000 },

            { order_id: 3, product_id: 5, price: 40000, quantity: 3, total: 120000 },
            { order_id: 3, product_id: 6, price: 60000, quantity: 1, total: 60000 },

            { order_id: 4, product_id: 7, price: 25000, quantity: 2, total: 50000 },
            { order_id: 4, product_id: 8, price: 35000, quantity: 1, total: 35000 },

            { order_id: 5, product_id: 9, price: 150000, quantity: 1, total: 150000 },
            {
                order_id: 5,
                product_id: 10,
                price: 100000,
                quantity: 2,
                total: 200000,
            },

            { order_id: 6, product_id: 11, price: 75000, quantity: 2, total: 150000 },
            { order_id: 6, product_id: 12, price: 40000, quantity: 1, total: 40000 },

            { order_id: 7, product_id: 13, price: 30000, quantity: 4, total: 120000 },
            { order_id: 7, product_id: 14, price: 50000, quantity: 1, total: 50000 },

            { order_id: 8, product_id: 15, price: 15000, quantity: 5, total: 75000 },
            { order_id: 8, product_id: 16, price: 20000, quantity: 1, total: 20000 },

            {
                order_id: 9,
                product_id: 17,
                price: 110000,
                quantity: 2,
                total: 220000,
            },
            { order_id: 9, product_id: 18, price: 30000, quantity: 1, total: 30000 },

            {
                order_id: 10,
                product_id: 19,
                price: 90000,
                quantity: 3,
                total: 270000,
            },
            { order_id: 10, product_id: 20, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 11,
                product_id: 21,
                price: 45000,
                quantity: 3,
                total: 135000,
            },
            { order_id: 11, product_id: 1, price: 30000, quantity: 1, total: 30000 },

            { order_id: 12, product_id: 2, price: 10000, quantity: 5, total: 50000 },
            { order_id: 12, product_id: 3, price: 20000, quantity: 1, total: 20000 },

            {
                order_id: 13,
                product_id: 4,
                price: 115000,
                quantity: 2,
                total: 230000,
            },
            { order_id: 13, product_id: 5, price: 30000, quantity: 1, total: 30000 },

            {
                order_id: 14,
                product_id: 27,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 14, product_id: 6, price: 50000, quantity: 1, total: 50000 },

            { order_id: 15, product_id: 1, price: 95000, quantity: 3, total: 285000 },
            { order_id: 15, product_id: 2, price: 50000, quantity: 1, total: 50000 },

            { order_id: 16, product_id: 3, price: 95000, quantity: 3, total: 285000 },
            { order_id: 16, product_id: 4, price: 50000, quantity: 1, total: 50000 },

            { order_id: 17, product_id: 5, price: 95000, quantity: 3, total: 285000 },
            { order_id: 17, product_id: 6, price: 50000, quantity: 1, total: 50000 },

            { order_id: 18, product_id: 7, price: 95000, quantity: 3, total: 285000 },
            { order_id: 18, product_id: 8, price: 50000, quantity: 1, total: 50000 },

            { order_id: 19, product_id: 9, price: 95000, quantity: 3, total: 285000 },
            { order_id: 19, product_id: 10, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 20,
                product_id: 11,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 20, product_id: 12, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 21,
                product_id: 13,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 21, product_id: 14, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 22,
                product_id: 15,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 22, product_id: 16, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 23,
                product_id: 17,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 23, product_id: 18, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 24,
                product_id: 19,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 24, product_id: 20, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 25,
                product_id: 21,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 25, product_id: 1, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 26,
                product_id: 2,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 26, product_id: 3, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 27,
                product_id: 25,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 27, product_id: 4, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 28,
                product_id: 15,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 28, product_id: 13, price: 50000, quantity: 1, total: 50000 },

            { order_id: 29, product_id: 1, price: 95000, quantity: 3, total: 285000 },
            { order_id: 29, product_id: 2, price: 50000, quantity: 1, total: 50000 },

            { order_id: 30, product_id: 3, price: 95000, quantity: 3, total: 285000 },
            { order_id: 30, product_id: 4, price: 50000, quantity: 1, total: 50000 },

            { order_id: 31, product_id: 5, price: 95000, quantity: 3, total: 285000 },
            { order_id: 31, product_id: 6, price: 50000, quantity: 1, total: 50000 },

            { order_id: 32, product_id: 7, price: 95000, quantity: 3, total: 285000 },
            { order_id: 32, product_id: 8, price: 50000, quantity: 1, total: 50000 },

            { order_id: 33, product_id: 9, price: 95000, quantity: 3, total: 285000 },
            { order_id: 33, product_id: 10, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 34,
                product_id: 11,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 34, product_id: 12, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 35,
                product_id: 13,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 35, product_id: 14, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 36,
                product_id: 15,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 36, product_id: 16, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 37,
                product_id: 17,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 37, product_id: 18, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 38,
                product_id: 19,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 38, product_id: 20, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 39,
                product_id: 11,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 39, product_id: 12, price: 50000, quantity: 1, total: 50000 },

            {
                order_id: 40,
                product_id: 13,
                price: 95000,
                quantity: 3,
                total: 285000,
            },
            { order_id: 40, product_id: 14, price: 50000, quantity: 1, total: 50000 },
        ];

        await OrderItem.bulkCreate(orderItems);

        console.log("Đã tạo thành công các OrderItems.");
    } catch (error) {
        console.error("Lỗi khi tạo dữ liệu:", error);
    }
};

// insertOrderItems();

async function insertData() {
    try {
        await sequelize.authenticate(); // Kết nối chỉ 1 lần
        console.log("Kết nối với database thành công.");

        await insertShippers();
        await insertUsers();
        await insertAddresses();
        await insertShops();
        await insertProducts();
        await insertOrders();
        await insertOrderItems1();
        await insertOrderItems();

        console.log("Tất cả dữ liệu đã được chèn thành công!");
    } catch (error) {
        console.error("Lỗi khi chèn dữ liệu:", error);
    } finally {
        await sequelize.close(); // Chỉ đóng kết nối sau khi tất cả các thao tác đã hoàn thành
        console.log("Đã đóng kết nối database.");
    }
}

// insertData();
// await insertShippers();
// await insertUsers();
// await insertAddresses();
// await insertShops();
// await insertProducts();
// await insertOrders();
// await insertOrderItems1();
// await insertOrderItems();
